### ISSUE TITLE
Question of paper

### ISSUE THREAD

**Issue by dyhBUPT** [NorahGreen/RTracker#1]
Hi, thanks for your excellent work.

I've read your paper and have a question about the description of PN tree.
What is meant by " contains a new target appearance" in Section 3.1. It equals to "tracking results with the positive label"?

**Comment by NorahGreen** [comment]
You can drop me an email for a detailed answer.

**Comment by dyhBUPT** [comment]
Oh, I've got the anwser from you in VALSE24, hhhh.

**Comment by NorahGreen** [comment]
lol, nice to see you!
